### ISSUE TITLE
SKProduct always null

### ISSUE THREAD

**Issue by xhardcorex** [qonversion/qonversion-ios-sdk#101]
I fetched list of products and  noticed that SKProduct inside QNProduct always null. I try to make purchase and get error - Error Domain=com.qonversion.io Code=2 "(null)".

```
 po self.products
▿ 1 element
  ▿ 0 : 2 elements
    - key : "sounds_monthly_7days_trial"
    - value : <QNProduct: id=sounds_monthly_7days_trial,
storeID=TygerSoundsMonthly,
type=0,
duration=1,
skProduct=(null),
>
```
```
Qonversion.purchase(product.qonversionID) { [weak self] (result, error, flag) in
            guard let self = self else { return }            
            if let error = error {
                completion(error)
                print(error.localizedDescription)
  }
```

**Comment by smejl** [comment]
Hi @xhardcorex. Could you please provide more details such as device and reproducing flow?

**Comment by xhardcorex** [comment]
Hi @smejl ! Thanks for quick response. Device info: iPhone XR (14.1). I run the following flow:
- Fetch products:
'''
    var products: [String: Qonversion.Product] = [:]
    func checkProducts() {
        Qonversion.products { [weak self] (result, error) in
            guard let self = self else { return }
            
            self.products = result
        }
    }
'''

- Try to purchase
'''
    func subscribePremium(completion: @escaping (Error?) -> Void) {
        if let product = self.products[Constants.productID] {
            Qonversion.purchase(product.qonversionID) { [weak self] (result, error, flag) in
            guard let self = self else { return }
            
            if let error = error {
                completion(error)
                print(error.localizedDescription)
            }
          }
        }
    }
'''

And after that I get error Error Domain=com.qonversion.io Code=2 "(null)".

**Comment by smejl** [comment]
Are you running on real device or simulator?

**Comment by xhardcorex** [comment]
Real device

**Comment by smejl** [comment]
Could you please check our [troubleshooting](https://documentation.qonversion.io/docs/troubleshooting#1-product-not-found-error) section **product not found error**? Please, tell us if that doesn't help.

**Comment by xhardcorex** [comment]
It doesn't help. I checked your troubleshooting yesterday and convinced that I configured SDK right.

**Comment by smejl** [comment]
Got it. Thanks. We will check and come back asap.

**Comment by suriksarkisyan** [comment]
Hi, @xhardcorex 
Can you, please, add a breakpoint at the first line of the function
`- (void)productsRequest:(nonnull SKProductsRequest *)request didReceiveResponse:(nonnull SKProductsResponse *)response` in `QNStoreKitService` and print `response.products` and `response.invalidProductIdentifiers`?
Looks like something wrong with inApp purchases config and Apple StoreKit does not return valid skProducts.

**Comment by xhardcorex** [comment]
<img width="518" alt="Screenshot 2020-12-18 at 8 32 02 PM" src="https://user-images.githubusercontent.com/10870335/102655603-40455300-417b-11eb-8d47-e40925a40472.png">
<img width="659" alt="Screenshot 2020-12-18 at 8 31 34 PM" src="https://user-images.githubusercontent.com/10870335/102655607-42a7ad00-417b-11eb-9073-d3531fd4686c.png">
<img width="603" alt="Screenshot 2020-12-18 at 8 30 26 PM" src="https://user-images.githubusercontent.com/10870335/102655612-43404380-417b-11eb-8ae0-44a7f4737a08.png">

**Comment by suriksarkisyan** [comment]
@xhardcorex thanks for the answer)
Looks like your in-app purchases were configured not correctly. 
Three most popular cases why you can receive `invalidIdentifiers` from Apple Store Kit:
1. Your in-app purchases are not configured correctly on the App Store Connect. Navigate to the App Store Connect, select your app, click Manage under the In-App Purchases title on the left menu. Check the value in the Status column. You should see Ready to submit status for correctly configured purchase.
2. Your app bundle ID does not match the bundle ID from App Store Connect where purchases were created.
3. You are using `.storekit` file which is configured with other IDs than you are trying to use.
