### ISSUE TITLE
Subscription status for different sandbox account on same device

### ISSUE THREAD

**Issue by saqibomer** [qonversion/qonversion-ios-sdk#110]
I created two different sandbox accounts. test1@sandbox.com and test2@sandbox.com. I purchased annual subscription using test1@sandbox.com, logged out from sandbox account and logged in with test2@sandbox.com. When I checked permissions using `Qonversion.checkPermissions` it shows me permission as active even though I have not purchased any subscription using test2@sandbox.com.

**Comment by smejl** [comment]
Hi, @saqibomer. We will try to reproduce that behaviour and come back shortly.

**Comment by saqibomer** [comment]
Any update on this one?

**Comment by DreamSkyMXDan** [comment]
Hi, Sam, any update on this issue? @smejl

**Comment by smejl** [comment]
Hi guys. 

We are researching the question. 
Looks like the only strong way to prevent that behavior is to make a refresh for a receipt every time on the launch. Unfortunately, that could worsen user experience because will prompt a user to sign in to their Apple ID if they are not signed in already.

Apple will not update receipt automatically after log out and log in. 
We could add option for making force refresh based on your configurations.

**Comment by saqibomer** [comment]
Instead of linking qid with device id, can't we link qid with custom user id?

**Comment by smejl** [comment]
What you mean and want to achieve with that?

**Comment by saqibomer** [comment]
How qid is generated for each user?

**Comment by smejl** [comment]
That wasn't generated, u updated user external id so was able to catch user based on user id.

**Comment by mspronk** [comment]
Hey @smejl , any update on this issue?

**Comment by smejl** [comment]
Hi @mspronk. 

We are working to support this corner case.  There will be an update over the coming weeks. I'm keeping this issue open for now, I'll be back after the update.

**Comment by suriksarkisyan** [comment]
Hi guys
@mspronk @saqibomer @DreamSkyMXDan 
Can you try to test that case again? Log out from Sandbox account and log in with another one. Also delete and install the app again, please.
Make sure you are using the latest version of our SDK.

**Comment by northelks** [comment]
@suriksarkisyan Hey, I have another case of the issue. I do Qonversion.purchase() of 1 product by one tester. And then, logout from that tester, login with another tester, run the app and calling Qonversion.checkPermissions() I'm getting purchased product of the tester1 (from tester2 account). I use the same device for both tester1 and tester2.

**Comment by suriksarkisyan** [comment]
Hi @northelks 
Yes, that's because you didn't reinstall the app and that's correct logic from Apple's point in that case. Apple doesn't replace `tester1` receipt after logout and `tester2` login until some StoreKit action (purchase/restore/etc).

**Comment by northelks** [comment]
@suriksarkisyan hm, I see, thank you for such quick response!
