### ISSUE TITLE
Force update user properties

### ISSUE THREAD

**Issue by saqibomer** [qonversion/qonversion-ios-sdk#116]
In [documentation](https://documentation.qonversion.io/docs/user-properties) it says

> How It Works

> Qonversion SDK gets user properties and sends data every 15 seconds, as well as when closing the app.

How can I force update user properties without waiting for 15 seconds or closing the app?

**Comment by smejl** [comment]
Qonversion updates user properties every 5 seconds. We've updated the docs. 

Why do you need to do this more often?

**Comment by saqibomer** [comment]
Consider this use case:
User test@user1.com registers a new account I set our custom user id to Qonversion. 
User logs out and registers another account test@user2.com. This user has different user id which I set to Qonversion. 
Now if I call https://api.qonversion.io/v2/users/user2_id this api returns resource not found. But after ~15 seconds it returns correct response i.e. subscription details.

**Comment by smejl** [comment]
That doesn't affect user accounts. User properties are just additional fields for your user. 

So you want to manage user accounts based on an external user id?

**Comment by smejl** [comment]
Closed as a duplicate for your previous issue.
