### ISSUE TITLE
Manifest

### ISSUE THREAD

**Issue by Alphebe** [qonversion/qonversion-ios-sdk#134]
<manifest>
    <application>
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ADMOB_APP_ID"/>
    </application>
</manifest>

**Comment by suriksarkisyan** [comment]
Hi @Alphebe 
Do you have any problems?

**Comment by Alphebe** [comment]
> Hi @Alphebe 
> Do you have any problems?

Yeah i do
