### ISSUE TITLE
InApp purchase via Qonversion in TestFlight doesn't work

### ISSUE THREAD

**Issue by DreamSkyMXDan** [qonversion/qonversion-ios-sdk#184]
We are testing our App in TestFlight and we found an issue. I paid one of the subscription plan in the App but I still cannot have premium service, in other words, Qonversion don't return any active status for me. I tested with our real apple Ids and also with Sandbox apple ids. None of them works in TestFlight.

This scenario works in the Non-TestFlight build or the debug build I deployed from Xcode.

**Comment by suriksarkisyan** [comment]
Hi @DreamSkyMXDan 
Looks like your in-app purchases are not valid for production mode. Please make sure you are submitting in-app purchases to review also.
Could you please provide more information about the problem? App name and in-app purchase id
Text me on s.sarkisyan@qonversion.io
I’ll check the problem and help you🙌

**Comment by DreamSkyMXDan** [comment]
All of my in app purchases are approved by Apple. Our App name is Care Linkage. How can we text you? Thanks

**Comment by suriksarkisyan** [comment]
@DreamSkyMXDan I will post the result here for other users that will face the same issue 🔧 
As we discussed, just make purchases and check permissions directly from SDK and not mix with API calls. That's the proper way to use SDK, and that works fine 🤝
