### ISSUE TITLE
Free trial duration shows as "Other" instead of "week"

### ISSUE THREAD

**Issue by akshaynhegde** [qonversion/qonversion-ios-sdk#213]
I have created two premium subscriptions. 
1. Monthly with 1 Week free trial 
2. yearly with 1 Month free trial

Both of these are configured the same way with introductory offers on the App store.  The yearly subscription has the right info whereas the monthly one doesn't show it correctly. 

Why is `QNTrialDuration` for 1 Week free trial is set to `QNTrialDurationOther` and not `QNTrialDurationWeek`?

```
▿ Optional<Array<QNProduct>>
  ▿ some : 2 elements
    - 0 : <QNProduct: id=premium_yearly_with_trial,
storeID=com.my_app.premium.yearly,
offeringID=main,
type=trial (enum value = 0),
duration=annual (enum value = 4),
trial duration=month (enum value = 4),
skProduct=<SKProduct: 0x280755ab0>,
>
    - 1 : <QNProduct: id=premium_monthly_with_trial,
storeID=com.my_app.premium.monthly,
offeringID=main,
type=trial (enum value = 0),
duration=monthly (enum value = 1),
trial duration=other (enum value = 9),
skProduct=<SKProduct: 0x2807559e0>,
>
```

<img width="1142" alt="Screenshot 2021-09-05 at 8 08 00 PM" src="https://user-images.githubusercontent.com/3814615/132130817-d04d88f2-bde6-48cb-bb99-c5c4e6b50416.png">

**Comment by suriksarkisyan** [comment]
Hi, @akshaynhegde 
I need a little bit more time to collect some information and come back with the answer. Let's keep in touch.

**Comment by suriksarkisyan** [comment]
Hi, @akshaynhegde 
Sorry for the late reply.
I've just tested a subscription with a one-week trial duration and got the correct result.
I'm not sure but in your case, the problem can be in the undocumented cache of StoreKit. I also faced strange behavior sometimes during the tests process. Did you try again after few minutes? Or could you please try again and let me know?
