### ISSUE TITLE
It is not possible to pass the quantity of the product in the purchase method

### ISSUE THREAD

**Issue by pgneri** [qonversion/qonversion-ios-sdk#219]
I'm using SwiftyStoreKit and I can't replace it with qonversion because it's not possible to send the amount when buying the product.

Today I have a tip product in the Apple Store, and I use this product over and over again to make the value more flexible by using multiple amounts to be able to buy several of the same product.
[SwiftyStoreKit](https://github.com/bizz84/SwiftyStoreKit#purchase-a-product-given-a-product-id
) and [StoreKit](https://developer.apple.com/documentation/storekit/skpayment/1506077-quantity
) support this.

It would be great if it was possible to send the quantity of the product that my users will buy.

**Comment by suriksarkisyan** [comment]
Hi, @pgneri 
Unfortunately, it's not possible right now. We'll add that feature in one of the next releases. But I can't give you an estimated date now. Let's keep in touch 🙌

**Comment by suriksarkisyan** [comment]
Hi there. I just want to say we released the [new version](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.12.0) with multiple in-app purchases support.
Use the new `Qonversion.shared().purchaseProduct()` function and pass the `Qonversion.PurchaseOptions` object to buy multiple in-app purchases.
```swift
let options = Qonversion.PurchaseOptions(quantity: 3)
Qonversion.shared().purchaseProduct(product, options: options) { entitlements, error, canceled in  
}
```
