### ISSUE TITLE
App freezes in iOS 15 on storefront call

### ISSUE THREAD

**Issue by gerchicov-bp** [qonversion/qonversion-ios-sdk#222]
From your code:
```
if (@available(iOS 13.0, macos 10.15, tvOS 13.0, *)) {
    NSString *countryCode = SKPaymentQueue.defaultQueue.storefront.countryCode ?: @"";
    purchaseDict[@"country"] = countryCode;
  }
```
Calling `storefront` on iOS freezes the app. It seems it is inner iOS bug but what about to add a possibility to disable `countryCode` to avoid such situations?

**Comment by suriksarkisyan** [comment]
Hi, @gerchicov-bp 
Thank you for the report 🤝
I'll check and come back with an answer.

**Comment by suriksarkisyan** [comment]
@gerchicov-bp I've just tested and can't get any freeze. Could you please provide the test scenario, Xcode and macOS version, all info you think important

**Comment by Maria-Bordunova** [comment]
Hi @gerchicov-bp 
Have you encountered the error again? If yes, could you please provide us with more details my colleague mentioned above.

**Comment by pixelfoxxx** [comment]
Hello @gerchicov-bp. We still didn't get your reply. We'll close this issue for the time being. Feel free to reopen this issue or create another one. We'll be glad to assist 🤝
