### ISSUE TITLE
App freezes when launch

### ISSUE THREAD

**Issue by pgneri** [qonversion/qonversion-ios-sdk#224]
Use code: `Qonversion.launch(withKey: <key>)`

<img width="1347" alt="Screen Shot 2021-12-02 at 00 28 00" src="https://user-images.githubusercontent.com/15379047/144352892-4077c141-d917-4c38-8dde-8e39ecf8790b.png">

**Comment by suriksarkisyan** [comment]
Hi @pgneri 
Could you please provide more information about which function freeze the app? What are you calling on the app start?

**Comment by pgneri** [comment]
Hi @suriksarkisyan, I'm just calling` Qonversion.launch(withKey:`

**Comment by suriksarkisyan** [comment]
@pgneri, it's strange because calling `Qonversion.launch ()` is our main flow, and you are the first one who asked about the problem. Also, we use that function in the sample app every day. Could you please provide additional info? OS version, simulator / real device, video (would be perfect), etc

**Comment by Maria-Bordunova** [comment]
Hi @pgneri.
Did you manage to deal with the issue? If not, could you please provide us with more details my colleague mentioned above.

**Comment by pixelfoxxx** [comment]
@pgneri Hello! We still didn’t get any reply from you regarding the issue above. We’ll close this issue for the time being.
Feel free to contact us if you have any further questions or if the issue persists. We’ll be glad to assist!
