### ISSUE TITLE
Same Permissions for different Login User ID's

### ISSUE THREAD

**Issue by atrsarankumar** [qonversion/qonversion-ios-sdk#252]
Use case:
I logged with UserA & I purchased subscription(3 months) using UserA. After that I logged out and logged in with UserB. When I called Qonversion.checkPermissions it shows same permissions for UserA as well as UserB.

I need to link my app's user id with Apple ID, how can I link that? 
I tried  to set below
 Qonversion.setProperty(.userID, value: user.uid)
 Qonversion.identify(user.uid)
 but permissions are same for different UserID's.

**Comment by SpertsyanKM** [comment]
Hello. I have checked right your case now and it works properly. We'll ask you for some detailed information via support (you've written us there too) to investigate your problem and try to figure out why it happens. 

About the second part of your question. If you want to link a user for analytics purposes, use `setProperty` - that id will be linked to the current user so you will be able to search for it in the dashboard. If you want to handle cross-platform access management - use `identity`. We will synchronize the permissions of users from different platforms or installs depending on their identity. In your case, you want UserB not to have permissions of UserA. It can be reached using the `identify` method.

**Comment by atrsarankumar** [comment]
ThanQ for Quick response
Iam calling these methods for Check permissions after login
        Qonversion.setProperty(.userID, value: user.uid)
        Qonversion.identify(user.uid)
        Qonversion.checkPermissions { (permissions, err) in
        }

and on logout am calling Qonversion.logout()

but same permissions am getting, please help me

**Comment by atrsarankumar** [comment]
Please let me know if any information needed from my side

**Comment by atrsarankumar** [comment]
Please let me know if any information needed from my side

**Comment by pixelfoxxx** [comment]
Hello @atrsarankumar. As we've already discussed in Intercom you might get the same permissions if you have purchased a product from one identity and called restore from another.

Let’s make one small experiment.
Could you please do the following:
1. remove the application with all its data and reinstall it.
2. from the clean app repeat this flow:
- Qonversion.setDebugMode()
- Qonversion.identify(id1)
- Qonversion.purchase()
- Qonversion.logout()
- Qonversion.identify(id2)
- Qonversion.checkPermissions()

But use new identities, which were not ever been used.

And tell us whether permissions differ for that users. The first user should be granted purchased permissions while the second one should have empty permissions.
