### ISSUE TITLE
Type 'Qonversion' has no member 'Automations'

### ISSUE THREAD

**Issue by ARFAOUI** [qonversion/qonversion-ios-sdk#320]
I'm getting the error when I compile. 

Xcode 14.2
Swift Package Manager

<img width="271" alt="Screenshot 2023-01-09 at 23 48 19" src="https://user-images.githubusercontent.com/1867492/211424668-a6ce916f-6188-4e67-9596-763f6933170b.png">
<img width="893" alt="Screenshot 2023-01-09 at 23 48 04" src="https://user-images.githubusercontent.com/1867492/211424673-e683f0fe-3fff-4b0c-8991-b014d643af5e.png">

**Comment by suriksarkisyan** [comment]
Hi, @ARFAOUI 
Thanks for contacting us! I'll try to reproduce and fix it ASAP

**Comment by suriksarkisyan** [comment]
Hi, @ARFAOUI 
Sorry for the late reply! Happy to say that the new release has been published. Please update to version [3.0.4](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/3.0.4).
