### ISSUE TITLE
QNUserDefaultsStorage.m - Line 41 -[QNUserDefaultsStorage loadObjectForKey:] + 41

### ISSUE THREAD

**Issue by seyfullahpolat** [qonversion/qonversion-ios-sdk#329]
Fatal Exception: NSInvalidUnarchiveOperationException
*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (QNLaunchResult) for key (root) because no class named "QNLaunchResult" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver

Qonversion ios sdk version is 3.0.2

**Comment by suriksarkisyan** [comment]
Hi, @seyfullahpolat 
Thanks for contacting us. This bug was fixed in the new version. Could you please update the SDK? 🙂

**Comment by seyfullahpolat** [comment]
Hi @suriksarkisyan which version this bug fixed?

**Comment by suriksarkisyan** [comment]
Fixed in [3.0.](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/3.0.3), but it would be better to update to the latest [3.1.0](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/3.1.0) version.

**Comment by seyfullahpolat** [comment]
Thak you so much
