### ISSUE TITLE
Qonversion.shared().purchaseProduct callback not being called

### ISSUE THREAD

**Issue by aleksey-ho** [qonversion/qonversion-ios-sdk#330]
I upgraded from version **2.20.0** to **3.1.0**, migrated according to the guide, I can get available subscriptions on startup using `Qonversion.shared().products`, I also get a callback in `Qonversion.shared().checkEntitlements` request.

However, when I call `Qonversion.shared().purchaseProduct` I get no response - the callback is not being called. I found these logs:
`Request failed: https://api.qonversion.io/v1/user/purchase, error: Error Domain=com.qonversion.io.api Code=3 "Internal error code: 10009." UserInfo={NSDebugDescription=Internal error code: 10009., NSLocalizedDescription=Could not store data
`

The worst thing is that after restarting I can't use the app, since Qonversion doesn't respond even at startup, when `Qonversion.shared().products` is called, the callback is no longer called and I can't even get available subscriptions. So the only solution is to reinstall the app and restart the iphone.

I tried `qonversionConfig.setEnvironment(.sandbox)` since I used `Qonversion.setDebugMode()` before but it didn't help.

iOS 15.0.2
Qonversion 3.1.0

**Comment by suriksarkisyan** [comment]
Hi, @aleksey-ho 
Could you please provide the scenario step by step? So I can reproduce and fix it ASAP.

**Comment by aleksey-ho** [comment]
@suriksarkisyan, calling `Qonversion.shared().products`, `Qonversion.shared().checkEntitlements`, no problem.
When calling `Qonversion.shared().purchaseProduct` apple purchase flow doesn't occur and the callback is not being called at all. After restarting the app any requests to `Qonversion.shared()` are not responded, I mean callback not being invoked, even `Qonversion.shared().products` nor `Qonversion.shared().checkEntitlements`.
The only solution is to reinstall the app and restart the iphone to get `Qonversion.shared().products` callback again.

It seems that it is somehow related to sandbox, because I actually succeeded to make a test purchase only after creating a sandbox account in apple sandbox testing. However, I don't understand why test purchases worked in 2.20.0 without creating a sendbox account. Maybe I'm doing something wrong, because the documentation says that the sandbox environment is optional.

**Comment by suriksarkisyan** [comment]
@aleksey-ho, thanks for the response. I just tried to reproduce it, and for me, it works fine. Could you please contact us via Intercom, and maybe we can plan a short call to explore, debug and fix the problem on call?

**Comment by aaparth** [comment]
@suriksarkisyan 

I am facing the same issue with the SDK and not receiving any values in entitlements while checking or purchasing the product even when the purchase was successful.

**Comment by SpertsyanKM** [comment]
@aaparth what SDK version do you use? 

Could you please share with us a step-by-step example to reproduce your issue? It would be even better if you could share a minimal reproducible example.

**Comment by aaparth** [comment]
@SpertsyanKM 

Thanks for you quick approach, I have managed to get it sorted. It was a mistake from our end as the Permissions were not setup.

**Comment by SpertsyanKM** [comment]
Just to clarify for any future requests - you have not set up Permissions in the product center and thus didn't receive any response on `checkEntitlements` call?

**Comment by erimfranci** [comment]
One of my users is experiencing the same issue where the Qonversion iOS SDK isn’t returning any response on checkEntitlements(), preventing the app from launching. @SpertsyanKM @aaparth, could you clarify what you mean by setting up permissions in the product center? Are you referring to the Qonversion product center or App Store Connect? 

Also, I’m currently using an older version of the Qonversion iOS SDK (3.4.2). Does this issue persist in the latest version of the SDK? I’m trying to decide whether it’s worth upgrading now to resolve this for the user or if I can wait until I have more time.

**Comment by SpertsyanKM** [comment]
I see, you've connected to our support - that's good, cause we'd need some additional information to check your case.
