### ISSUE TITLE
Crash: NSInvalidUnarchiveOperationException

### ISSUE THREAD

**Issue by MacMark** [qonversion/qonversion-ios-sdk#345]
Dear Qonversion devs,

the most frequent crash in our app is currently this one. The SDK version is 2.21.1. Is this a known issue?

We had Qonversion 2.21.1 in app version 5.6.18 and did not notice such a crash.
Then we used Qonversion 3.2.1 in app version 5.6.19 but we decided to roll this app back to .18.
We see this crash in app version 5.6.20 which is a new build of the 5.6.18 code base. Could this cause the issue?

Kind regards,
Markus

Fatal Exception: NSInvalidUnarchiveOperationException
*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (QONLaunchResult) for key (root) because no class named "QONLaunchResult" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver

Fatal Exception: NSInvalidUnarchiveOperationException
0  CoreFoundation                 0x9a34 __exceptionPreprocess
1  libobjc.A.dylib                0x15958 objc_exception_throw
2  Foundation                     0x4b04ac -[NSCoder __failWithException:]
3  Foundation                     0x4b05e4 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:]
4  Foundation                     0x44f60 _decodeObjectBinary
5  Foundation                     0x1ea40 _decodeObject
6  Foundation                     0x47aac -[NSKeyedUnarchiver decodeObjectForKey:]
7  Foundation                     0xb3df4 +[NSKeyedUnarchiver unarchiveObjectWithData:]
8  Qonversion                     0x1e34c (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
9  Qonversion                     0x10e04 (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
10 Qonversion                     0x10ee0 (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
11 Qonversion                     0x14c8c (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
12 Qonversion                     0x11388 (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
13 Qonversion                     0x15f88 (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
14 Qonversion                     0x7230 (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
15 Qonversion                     0x8704 (Missing UUID 13bc0e8f2a6c313985aba580349bdcfa)
16 CFNetwork                      0x1e1f4 CFURLRequestSetMainDocumentURL
17 CFNetwork                      0x2dabc _CFNetworkErrorCopyLocalizedDescriptionWithHostname
18 libdispatch.dylib              0x63850 _dispatch_call_block_and_release

**Comment by suriksarkisyan** [comment]
Hi, @MacMark 
The problem relates to rollback from the higher version (where QONLaunchResult class is available) to the lower version (where the class is named QNLaunchResult). Unfortunately, covering major version migration from the higher to the lower is a little bit hard and unexpected. Why did you decide to migrate from 3.2.1 to 2.21.1? Did you face any issues?

**Comment by MacMark** [comment]
Indeed the issue was solved by releasing the app again with the latest Qonversion SDK.
