### ISSUE TITLE
For what reasons would I get a "Fraud purchase detected" error?

### ISSUE THREAD

**Issue by brainfuel** [qonversion/qonversion-ios-sdk#347]
Title says it all. 

Error Domain=com.qonversion.io.api Code=8 "Internal error code: 10008." UserInfo={NSDebugDescription=Internal error code: 10008., NSLocalizedDescription=Fraud purchase detected}

**Comment by brainfuel** [comment]
This is not an error in the wild. The app has not been released and I'm just trying to set it all up. However, when I test a purchase I get this error, and not sure why.

**Comment by pixelfoxxx** [comment]
Hello @brainfuel, 

Thank you for the report. Could you please provide me with something to help me determine the issue better (Qonversion User ID, Project Name)? You can contact me via Intercom live chat to look deeper.

**Comment by pixelfoxxx** [comment]
Could you please also clarify whether you're using the StoreKit configuration file for testing subscriptions?
