### ISSUE TITLE
Catch deferred state while purchasing

### ISSUE THREAD

**Issue by fury21** [qonversion/qonversion-ios-sdk#392]
XCode Version 14.3.1 (14E300c)
QOnversion via SPM

In XCode project in method  "Qonversion.shared().purchaseProduct(product) { (entitlements, error, isCancelled) in" i try cast error to Qonversion.Error to catch deferred state, but when i try to build project i got message: 
"Undefined symbols for architecture arm64:
  "_QONErrorDomain", referenced from:
      _$sSC8QONErrorLeV11errorDomainSSvgZ in IAPManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
"

as soon as I remove the line "  if let error = error as? Qonversion.Error {" the project builds normally.

How can i catch deferred state? 
The help on the website dedicated to the deferred purchase does not explain anything

**Comment by suriksarkisyan** [comment]
Hi, @fury21 
You can check it like this:
```swift
if let error = error as? NSError, error.code == Qonversion.Error.storePaymentDeferred.rawValue {
    // handle deferred purchase
}
```

**Comment by fury21** [comment]
QONErrorCancelled = 1 and isCancelled (in onversion.shared().purchaseProduct(product) { (entitlements, error, isCancelled) ) it's same ?

**Comment by suriksarkisyan** [comment]
> QONErrorCancelled = 1 and isCancelled (in onversion.shared().purchaseProduct(product) { (entitlements, error, isCancelled) ) it's same ?

Yes, it is. We just added an additional `isCancelled` flag to simplify the logic. But you can use a comparison with QONErrorCancelled as well.

**Comment by suriksarkisyan** [comment]
> How can i test (or simulate) "Ask to buy" request? Is it possible?

Ask to buy works the same as an auto-renew of subscription (and deferred purchases). So if you already tested the auto-renew, there is no need to test ask to buy separately. The only thing you need to do is implement following function:
https://documentation.qonversion.io/docs/deferred-purchases

**Comment by fury21** [comment]
♡
