### ISSUE TITLE
(MacOS) Offline caching for entitlements hasn't worked yet

### ISSUE THREAD

**Issue by petiatil** [qonversion/qonversion-ios-sdk#406]
I've tried with Xcode 14.2 and 14.3.1. MacOS Ventura 13.5.2, (testing on real device) 2019 MacBook Pro, built with the App Sandbox capability

I've tried Qonversion 5.0.0, 5.1.x, and 5.2.0, and have gotten the same result. (I subscribe, subscription is verified [i.e. still subscribed when rebuilding/relaunching the app], except when offline.)

I've tried testing with importing Qonversion vs QonversionSwift, and installing via Podfile vs SPM.

Some relevant screenshots (including console output when attempting to retrieve entitlements when offline):

<img width="1201" alt="Config" src="https://github.com/qonversion/qonversion-ios-sdk/assets/79606930/8710bb9d-b8a9-4750-af7b-7e1e76a89155">
<img width="856" alt="checkEntitlements definition" src="https://github.com/qonversion/qonversion-ios-sdk/assets/79606930/7afc4ee5-7997-4e29-8128-872afea8d950">
<img width="1617" alt="Start checking entitlements" src="https://github.com/qonversion/qonversion-ios-sdk/assets/79606930/f6d25518-cbb7-465d-8848-2f773ee92923">
...

<img width="1624" alt="Finish checking entitlements" src="https://github.com/qonversion/qonversion-ios-sdk/assets/79606930/f85df573-acd1-4a5b-9928-43d4a43d5390">

Side notes: 

- The documentation example (at https://documentation.qonversion.io/docs/offline-sdk-mode) doesn't use .sandbox mode
- If it matters: This is a macOS app, but not Catalyst

**Comment by suriksarkisyan** [comment]
Hi! Sorry for the late reply. I'll try to reproduce the issue on MacOS and come back with an update.
