### ISSUE TITLE
Missing exported `QONErrorDomain` constant

### ISSUE THREAD

**Issue by megastep** [qonversion/qonversion-ios-sdk#411]
Just ran into this issue trying to parse `NSError` returned by the SDK (version 5.2.0).

It appears that the `QONErrorDomain` constant is not defined anywhere publicly in the SDK, so referencing it in my code to check the domain of errors prevents my app from linking.

This line from `QONErrors.h`:

```objc
extern NSErrorDomain const QONErrorDomain NS_SWIFT_NAME(Qonversion.ErrorDomain);
```

There is no corresponding symbol declaration in the module. It feels like it should be in `QONErrors.m` and be set to the value of the private internal constant `keyQONErrorDomain`. I'm not sure what your conventions are for this but it should be trivial enough to fix.

**Comment by megastep** [comment]
This relates to issue #392 and would allow regular type checking to work in Swift. If we don't check for the domain there is a potential for collisions with other error domains.

**Comment by suriksarkisyan** [comment]
Hi, @megastep 
Thanks for the issue. You are right; we should add public const. I think we can do it in the next update.

**Comment by suriksarkisyan** [comment]
Hi, @megastep 
Thanks again for creating this issue, and I am happy to say that in the [last version](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.3.0) of our SDK, you can use two constants: `QonversionErrorDomain, QonversionApiErrorDomain` to determine what kind of error is happened.
