### ISSUE TITLE
try await Qonversion.shared().offerings(): Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by shalom-aviv** [qonversion/qonversion-ios-sdk#422]
revision : d95285898b2f5258261c62e2579d4c721f5d804b
version : 5.4.0
ios simulator: iPhone 15 iOs 17.0

- Try to get offers via modern concurrency

<img width="1087" alt="Screenshot 2023-12-08 at 12 28 18" src="https://github.com/qonversion/qonversion-ios-sdk/assets/78256107/290aeac4-0600-4891-8b59-1d72c290f845">

- No offers on server

<img width="1087" alt="Screenshot 2023-12-08 at 12 28 18" src="https://github.com/qonversion/qonversion-ios-sdk/assets/78256107/d766fdd0-ff49-449f-81ba-693a24abb40e">

- `try await Qonversion.shared().offerings()` This line should return not nil value or throw exception. In current case there no value, no any exceptions only crash ;)
<img width="839" alt="Screenshot 2023-12-08 at 12 38 23" src="https://github.com/qonversion/qonversion-ios-sdk/assets/78256107/33c48f5f-a44d-45c8-bccc-77f73b226ab0">

**Comment by suriksarkisyan** [comment]
Hi, @shalom-aviv 
Could you please contact us via Intercom on our website and share more details about your project? We need more information to understand the problem, and that data is too personal to be shared here.

**Comment by shalom-aviv** [comment]
@suriksarkisyan 

Hi

In the application profile, offers were not configured. 
They were not present at all, only purchases and entitlements.

Now an offer has been added and everything is working fine. 
I don't have access to the application's admin panel, only the key. 
I wrote in your system and left a link to this task in the repository.

**Comment by suriksarkisyan** [comment]
Hi, @shalom-aviv 
You are correct. The problem arises only when offerings are requested while they have not been created in the dashboard. We have released a new version [5.12.4](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.12.4) of our SDK, and now a corresponding error will be returned in such cases.
