### ISSUE TITLE
Data Races in QNUserPropertiesManager

### ISSUE THREAD

**Issue by Ralph1300** [qonversion/qonversion-ios-sdk#443]
We recently experienced some data races in the QNUserPropertiesManager class. We are using Xcode 15 and have the Thread Sanitizer activated for debug builds.

See the attached screenshot for an example. This is usually triggered right after the app start, where we call `Qonversion.initWithConfig()` from the main thread in the AppDelegate.

As far as I can tell issues are related to 
```
@property (nonatomic, assign, readwrite) BOOL sendingScheduled;
@property (nonatomic, assign, readwrite) BOOL updatingCurrently;
```

Both properties are read/written to on multiple occasions - sometimes `updatingCurrently` is wrapped in a synchronization block, but not always. For `sendingScheduled` this is missing completely.

![Stack](https://github.com/qonversion/qonversion-ios-sdk/assets/7126326/16d2ed0a-63c5-4341-b46f-bd3d8bbef599)

Thanks for looking into this, and let me know if you need more input!

**Comment by suriksarkisyan** [comment]
Hi, @Ralph1300 
Thanks for the details. We will look deeper into this issue and come back with an update!

**Comment by Ralph1300** [comment]
@suriksarkisyan any news? Issue got closed automatically now.

**Comment by suriksarkisyan** [comment]
> @suriksarkisyan any news? Issue got closed automatically now.

We reopened this issue. It's still in progress. We will try to fix it in the next release. And could you please give me some examples of usage of our properties code?

**Comment by SpertsyanKM** [comment]
Although we couldn’t replicate any race conditions in the user properties manager, we’ve implemented a few fixes to mitigate potential issues. We recommend upgrading to Qonversion SDK version [5.12.5](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.12.5). I’ll close this issue for now, but don’t hesitate to reopen it or submit new ones if you have any questions.

And thank you for bringing this to our attention!
