### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by iharkatkavets** [qonversion/qonversion-ios-sdk#461]
Privacy Updates for AppStore submission

## Expected Behavior
Developers are responsible for all code included in their apps. At WWDC23, Apple introduced new privacy manifests and signatures for commonly used third-party SDKs and announced that developers will need to declare approved reasons for using a set of APIs in their app’s privacy manifest.

## Current Behavior
The library doesn't provide Privacy Manifest file

## Possible Solution
The library should provide Privacy Manifest if it collects information or access "Required Reasons API"

## Additional Info
<img width="826" alt="Screenshot 2024-03-08 at 09 26 02" src="https://github.com/qonversion/qonversion-ios-sdk/assets/1083951/4b9c1e1c-52d4-44d1-b861-247896a82e19">

**Comment by suriksarkisyan** [comment]
Hi, @iharkatkavets !
We will update our SDK and add the Privacy manifest file ASAP! Let's keep in touch 🤝

**Comment by suriksarkisyan** [comment]
Hi, @iharkatkavets 
We released a new version [5.8.2](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.8.2) with Privacy manifest support!
