### ISSUE TITLE
'QONRemoteConfigList+Protected.h' file not found

### ISSUE THREAD

**Issue by c128128** [qonversion/qonversion-ios-sdk#498]
`'QONRemoteConfigList+Protected.h' file not found` when I try to install it with SPM. Version `5.8.4`.

Looks like the problem is because my machine is APFS (Case-sensitive). And your file name is `...+protected.h` lowercased :)

**Comment by SpertsyanKM** [comment]
Hello, @c128128. Thanks for contacting us and revealing this problem. The fix is already available in the release [5.8.5](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.8.5). Please, consider upgrading your version.
