### ISSUE TITLE
Warning: Umbrella header for module 'Qonversion' does not include header 'QONPromotionalOffer.h'

### ISSUE THREAD

**Issue by HassanTaleb90** [qonversion/qonversion-ios-sdk#532]
V: 5.12.0

<img width="1043" alt="Screenshot 2024-08-19 at 8 04 16 PM" src="https://github.com/user-attachments/assets/664ef4ef-21e3-479c-b0d0-794295b65648">

**Comment by HassanTaleb90** [comment]
Could this warning cause any issues with my app when I launch it?

**Comment by suriksarkisyan** [comment]
Could this warning cause any issues with my app when I launch it?
No, it couldn't. It's just a warning.

**Comment by suriksarkisyan** [comment]
Hi. This warning was fixed in the [new 5.12.1 version](https://github.com/qonversion/qonversion-ios-sdk/releases/tag/5.12.1).
