### ISSUE TITLE
Invalid duration of products - iOS SDK

### ISSUE THREAD

**Issue by saqibomer** [qonversion/qonversion-ios-sdk#94]
Product list shows invalid duration. I have an annual and quarterly product defined in product centre. Response shows duration as 2 and 4. 

```
Qonversion.products { productsList, error in
     print(productsList)
}
```
And here is response 
```
key: "premium_plan_quarterly", value: <QNProduct: id=premium_plan_quarterly,
storeID=premium_plan_quarterly,
type=1,
duration=2,
skProduct=<SKProduct: 0x28075ccf0>,
>
```

**Comment by suriksarkisyan** [comment]
Hi, @saqibomer 
That's how Enum's works in Objective-C.
Obj-C supports only Int enums and as you can see in QNProductDuration, QNProductDurationAnnual is equal 4 and QNProductDuration3Months is equal 2.
But the misunderstanding is possible so in the next SDK update we will add more info for Enums printing in log. I think we can print string value and raw (int) value for Enums like QNProductDuration.

**Comment by saqibomer** [comment]
I figured it out it was enum not actual duration. It would be good it instead of enums we get string and int values.

**Comment by suriksarkisyan** [comment]
What reason do you need the string value for? For using in the code or just for more understanding in the code and logs?
We can not add universal string value that can be used in code and UI for all of our users. Basically developers just checking enum value and configuring the text for UI by themselves.
But as i said, we will add string value for logs.
