### ISSUE TITLE
skProduct is null some times

### ISSUE THREAD

**Issue by saqibomer** [qonversion/qonversion-ios-sdk#98]
I am using sandbox account and can successfully get products and permission from Qonversion. But sometimes I get `skProduct` null for some products. Conversion shows product info after couple of times I relaunch the app.

**Comment by suriksarkisyan** [comment]
Hi, @saqibomer can you show an example of getting products? 
Are you using `Qonversion.products()` for it or just products from the launch result?

**Comment by smejl** [comment]
See #101
